### ISSUE TITLE
Chapter 3 - page 69 - Updating the Cars Controller File

### ISSUE THREAD

**Issue by ahuimanu** [aaronksaunders/AppC-Alloy-Book-Misc#1]
As it seems that Collection.getByCid is depreceated (and furthermore the print and kindle versions have a typo where you call the method _getByCid rather than getByCid, this entire example (in chapter 3) needs an update.

```
//get the correct model
var model = Alloy.Collections.cars.getByCid(_event.rowData.modeId);
```

It is nice that you have some of the book's code here in GitHub, but would it be possible to get each of the examples of code up to this repo?

Chapter 2 and 3 have been frustrating as there are quite a few typos (print and kindle). 

There are SO FEW books covering this topic, it would be nice to have one that is free of syntax errors.

In any case, please advise on the update to this.

Thanks!

**Comment by aaronksaunders** [comment]
I will take a look, but feel free to submit a pull request.  Please understand this text/code was written over a year ago and software updates a lot faster than the publishing industry. The publishers did not require this code to be posted, I posted it myself so that it could help others. 

I will take a look some time this week and try to make the updates.

**Comment by ahuimanu** [comment]
Thanks.

I am using your book to teach a class, so I suppose I'll be finding things
here and there.  It would still be nice to get this source up entirely on
Github.  As I find errata, I'll use Github to try to help.

Thanks for the reply.

**Comment by aaronksaunders** [comment]
@ahuimanu i will be making the updates today and this weekend, please be sure to log the specifics of the issues here so i can fix them and update the repo... I am also using the book for a class  I am teaching!

Is there any information you can provide on the class? You can contact me directly at aaron@clearlyinnovative.com

**Comment by aaronksaunders** [comment]
the updates have been made

**Comment by frodfigu** [comment]
Hi, Aaron, nice book. Same issue here. I can´t work this example. Alloy.Collections.cars.get returns null value and .getByCid crash the app and close it. Can you help me?

I cant post the issue on the chapter03 code. Sorry...

**Comment by aaronksaunders** [comment]
@frodfigu this issue has been resolved? what version of Appcelerator are you using and what device are you on - also i opened up the repo for Issues.- https://github.com/aaronksaunders/AppC-Alloy-Book-Chapter03

**Comment by frodfigu** [comment]
No, it isn´t. Appcelerator Titanium SDK 3.5.0.GA. iOS Simulator with iPhone 6 with iOS 8.1.
Thank you very much for your support.
Regards.

**Comment by frodfigu** [comment]
Same on 3.4.0...

**Comment by aaronksaunders** [comment]
i dont know what code you are running... I just pulled the repo and the
code runs fine. https://github.com/aaronksaunders/AppC-Alloy-Book-Chapter03

## -- http://www.clearlyinnovative.com/build-it/

Aaron K. Saunders
CEO Clearly Innovative Inc.
aaron@clearlyinnovative.com
201.214.5926  (M)
blog@clearlyinnovative.com
www.clearlyinnovative.com
@aaronksaunders

This email message and any attachment(s) are for the sole use of the
intended recipient(s) and may contain proprietary and/or confidential
information which may be privileged or otherwise protected from disclosure.
Any unauthorized review, use, disclosure or distribution is prohibited. If
you are not the intended recipient(s), please contact the sender by reply
email and destroy the original message and any copies of the message as
well as any attachment(s) to the original message.

**Comment by frodfigu** [comment]
Yep! Your code runs ok... the only difference is the navigationWindow. I´m using a simple window.open for a modal window.

Thanks!!
